import type { TrimSize, TrimSizeId } from '../types/book';

export const TRIM_SIZES: Record<TrimSizeId, TrimSize> = {
  waziri: {
    id: 'waziri',
    nameArabic: 'الحجم الوزيري (17×24 سم)',
    nameEnglish: 'Waziri Standard (170×240 mm)',
    widthMm: 170,
    heightMm: 240,
    description: 'المقاس الكلاسيكي المعتمد في دور النشر العربية لأمهات الكتب والدراسات والأبحاث الفكرية والتاريخية.',
    marginTopMm: 22,
    marginBottomMm: 25,
    marginInnerMm: 26, // gutter for binding
    marginOuterMm: 18, // outer edge
    defaultFontSizePt: 14,
    defaultLineHeight: 1.75,
  },
  medium: {
    id: 'medium',
    nameArabic: 'الحجم المتوسط (14×21 سم)',
    nameEnglish: 'Trade / Medium (140×210 mm)',
    widthMm: 140,
    heightMm: 210,
    description: 'المقاس الأكثر رواجاً للروايات وكتب المقالات والدراسات الفلسفية والأدبية الحديثة.',
    marginTopMm: 18,
    marginBottomMm: 20,
    marginInnerMm: 22,
    marginOuterMm: 15,
    defaultFontSizePt: 13,
    defaultLineHeight: 1.7,
  },
  a5: {
    id: 'a5',
    nameArabic: 'مقاس A5 القياسي (14.8×21 سم)',
    nameEnglish: 'ISO A5 (148×210 mm)',
    widthMm: 148,
    heightMm: 210,
    description: 'المقاس المكتبي والدولي الشائع، سهل الطباعة في المطابع الرقمية والتوزيع.',
    marginTopMm: 18,
    marginBottomMm: 20,
    marginInnerMm: 22,
    marginOuterMm: 16,
    defaultFontSizePt: 13,
    defaultLineHeight: 1.7,
  },
  quarto: {
    id: 'quarto',
    nameArabic: 'المجلد الموسوعي (20×27 سم)',
    nameEnglish: 'Crown Quarto (200×270 mm)',
    widthMm: 200,
    heightMm: 270,
    description: 'مقاس المجلدات الكبيرة والموسوعات والمعاجم والكتب ذات الحواشي الكثيفة ومخطوطات التراث.',
    marginTopMm: 25,
    marginBottomMm: 28,
    marginInnerMm: 30,
    marginOuterMm: 22,
    defaultFontSizePt: 15,
    defaultLineHeight: 1.8,
  },
  pocket: {
    id: 'pocket',
    nameArabic: 'كتاب الجيب (11.5×18 سم)',
    nameEnglish: 'Pocket Book (115×180 mm)',
    widthMm: 115,
    heightMm: 180,
    description: 'حجم مدمج وخفيف للكتيبات والرسائل الفكرية المختصرة والقراءات السريعة.',
    marginTopMm: 15,
    marginBottomMm: 16,
    marginInnerMm: 18,
    marginOuterMm: 12,
    defaultFontSizePt: 11.5,
    defaultLineHeight: 1.6,
  },
};
